--getNoticeList
SELECT * FROM (
	SELECT ROWNUM NUM, n.*
	FROM (SELECT * FROM NOTICE1 ORDER BY REGDATE DESC) n
)
WHERE NUM BETWEEN 6 AND 10;

SELECT * FROM (
	SELECT ROW_NUMBER () OVER (ORDER BY REGDATE DESC) NUM,
			NOTICE1.* FROM NOTICE1
)
WHERE NUM BETWEEN 6 AND 10;

--getNoticeCount

--getNotice

--getNextNotice
SELECT * FROM NOTICE1
WHERE id = (
	SELECT ID FROM NOTICE1
	WHERE REGDATE > (SELECT REGDATE FROM NOTICE1 WHERE id = 3)
	AND rownum = 1
);
DELETE NOTICE1 WHERE id = 4;

SELECT * FROM NOTICE1 ORDER BY REGDATE;

--getPrevNotice
SELECT * FROM (
	SELECT ID FROM notice1
	WHERE REGDATE < (SELECT regdate FROM notice1 WHERE id = 3 )
	ORDER BY id DESC
)
WHERE rownum = 1;

SELECT * FROM (SELECT * FROM NOTICE1 ORDER BY REGDATE desc)
WHERE regdate < (SELECT regdate FROM notice1 WHERE id = 3)
AND rownum = 1;

UPDATE notice1 SET regdate = TO_DATE('2021-02-07 15:30:30', 'YYYY-MM-DD HH24:MI:SS') WHERE id = 1;

SELECT * FROM notice1 ORDER BY id desc;
INSERT INTO notice1
VALUES (34,'JSP를 활용한 게시판 만들기1','newlec','게시판을만들기위해....',
to_date('2021-11-01 10:20:10','YYYY-MM-DD HH24:mi:ss'), 0,'',0);

VALUES (?,?,?,?,to_date(?,'YYYY-MM-DD HH24:mi:ss'), ?,?,?)



SELECT * FROM NOTICE1;

SELECT * FROM (
	SELECT rownum num, n.* FROM (
		SELECT * FROM NOTICE1 WHERE title LIKE '%test%' ORDER BY regdate DESC
	) n
)
WHERE num BETWEEN 1 AND 10;


SELECT * FROM NOTICE1 WHERE title LIKE '%test%' ORDER BY regdate DESC;

SELECT COUNT(ID) count FROM (
	SELECT ROWNUM NUM, n.*
	FROM (SELECT * FROM NOTICE1 WHERE title LIKE '%2%' ORDER BY REGDATE DESC) n
) n;

SELECT count(ID) count FROM (
	SELECT * FROM NOTICE1 WHERE title LIKE '%2%' ORDER BY regdate DESC
);

SELECT * FROM COMMENT1;
SELECT * FROM MEMBER1;
SELECT * FROM NOTICE1;

INSERT INTO MEMBER1 
values('dragon', '1234', '드래곤', '남', sysdate, '010-1234-5678', sysdate, 'asdf@nadsf');
INSERT INTO MEMBER1 
values('newlec', '1234', '뉴렉', '남', sysdate, '010-1234-5678', sysdate, 'asdf@nadsf');

INSERT INTO COMMENT1 VALUES (1, '내용무', sysdate, 'dragon', 59);
INSERT INTO COMMENT1 VALUES (2, '내용무', sysdate, 'newlec', 58);
INSERT INTO COMMENT1 VALUES (3, '내용무', sysdate, 'dragon', 59);
INSERT INTO COMMENT1 VALUES (4, '내용무', sysdate, 'newlec', 59);
INSERT INTO COMMENT1 VALUES (5, '내용무', sysdate, 'dragon', 57);


SELECT * FROM NOTICE1 N
LEFT JOIN COMMENT1 C ON N.ID = C.NOTICE_ID
ORDER BY N.REGDATE desc;


SELECT N.ID, N.TITLE, N.WRITER_ID, N.REGDATE, N.HIT, N.FILES, COUNT(C.ID) cmt_count
FROM NOTICE1 N
LEFT JOIN COMMENT1 C ON N.ID = C.NOTICE_ID
GROUP BY N.ID, N.TITLE, N.WRITER_ID, N.REGDATE, N.HIT, N.FILES
ORDER BY N.REGDATE DESC;

CREATE VIEW NOTICE_VIEW
AS
SELECT N.ID, N.TITLE, N.WRITER_ID, N.REGDATE, N.HIT, N.FILES, COUNT(C.ID) cmt_count
FROM NOTICE1 N
LEFT JOIN COMMENT1 C ON N.ID = C.NOTICE_ID
GROUP BY N.ID, N.TITLE, N.WRITER_ID, N.REGDATE, N.HIT, N.FILES;
SELECT * FROM NOTICE1_VIEW;


SELECT * FROM (
	SELECT ROWNUM NUM, n.*
	FROM (SELECT * FROM NOTICE_VIEW WHERE title LIKE '%%' ORDER BY REGDATE DESC) n
) 
WHERE NUM BETWEEN 1 AND 100;