--getNoticeList
SELECT * FROM (
	SELECT ROWNUM NUM, n.*
	FROM (SELECT * FROM NOTICE1 ORDER BY REGDATE DESC) n
)
WHERE NUM BETWEEN 6 AND 10;

SELECT * FROM (
	SELECT ROW_NUMBER () OVER (ORDER BY REGDATE DESC) NUM,
			NOTICE1.* FROM NOTICE1
)
WHERE NUM BETWEEN 6 AND 10;

--getNoticeCount

--getNotice

--getNextNotice
SELECT * FROM NOTICE1
WHERE id = (
	SELECT ID FROM NOTICE1
	WHERE REGDATE > (SELECT REGDATE FROM NOTICE1 WHERE id = 3)
	AND rownum = 1
);
DELETE NOTICE1 WHERE id = 4;

SELECT * FROM NOTICE1 ORDER BY REGDATE;

--getPrevNotice
SELECT * FROM (
	SELECT ID FROM notice1
	WHERE REGDATE < (SELECT regdate FROM notice1 WHERE id = 3 )
	ORDER BY id DESC
)
WHERE rownum = 1;

SELECT * FROM (SELECT * FROM NOTICE1 ORDER BY REGDATE desc)
WHERE regdate < (SELECT regdate FROM notice1 WHERE id = 3)
AND rownum = 1;

UPDATE notice1 SET regdate = TO_DATE('2021-02-07 15:30:30', 'YYYY-MM-DD HH24:MI:SS') WHERE id = 1;


